before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: q1xP1P11FGRBEq73Aa70HfGpPyQ786xjLWs9IRktFW4jzFTfX2gikLTSbvZ/N2QSfUodPNqj8E2/XlyqIXb8kD1Wa6iL8PlszFQi/z4esRFMwJmjfCKtbtoWmXcyzmemcICSTmgu+6Kv+uDO/d9pbJXK57Nv309TCM8rGVDkjINso1kVv0xlfAdARt8yFmCgPPwbJVhJGnPIJcYmAK2cXRuS5AJ0MO8jYFloE4/1hJ0RseItlqBPq04fO5FtEREWNQDmZGWV5WdkYmOyfnp5GLpIV8dz5wpVUcXBhhkIoBW2rZOsc9ahQAEQo08n9juM5uUVMfMfxCUZju5308pKTBuNCFd4lfEZ7Qg6jbpP0HwKu2a/pI/DkcpOytjpZnVlvkpiB5Um+U+HkXk7y0CrdURjNUjqzsrqv/Jfxv25AFgbkveQ2YElZB3O9gcCHnsouDE1ekjDlAC3I8cckiAGEsQoXRWxZlNds7IB8azGYOsjvelSuZu+ILPEoj2Nl16UmGvcDqn7Z6vMQ4Y7PxAwaD0mRGbNrNkra/UvS4WSSlMEpx5xd9KZ0v3zku3SVLwMj6LmY1e+kx5i/sDhLd3pW8tJW4tM3mPZ72YoGk/IpQ3v0UC9k9KyNzNz0zqPrpa8NMKmqwEm4uYgr1b10yzZi1JGk0793iOx6evHO9lQEd0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
